name: Sync and Release Clang Toolchains

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Maximize build space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc

    - name: Download Clang r522817 (Clang 18 / vili SM8350)
      run: |
        curl -L --connect-timeout 15 --retry 5 \
          "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r522817.tar.gz" \
          -o clang-r522817.tar.gz
        
    - name: Download Clang r547379 (Clang 20 / sapphire SM6225)
      run: |
        curl -L --connect-timeout 15 --retry 5 https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz -o clang-r547379.tar.gz
        
    - name: Download Clang r563880c (Clang 21 / rtwo SM8550)
      run: |
        curl -L --connect-timeout 15 --retry 5 "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/heads/android16-qpr2-release/clang-r563880c.tar.gz" -o clang-r563880c.tar.gz

    - name: Verify Downloads
      run: |
        ls -lh *.tar.gz

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: clang-${{ github.run_number }}
        name: "Clang Toolchains (r547379 & r563880c)"
        body: |
          ## Automated Clang Toolchains Release
          
          ### Binaries Included:
          * **Clang r522817** (Clang 18 / vili SM8350 NonGKI)    
          * **Clang r547379** (Clang 20 / sapphire SM6225)
          * **Clang r563880c** (Clang 21 / rtwo SM8550)
          
        draft: false
        prerelease: false
        files: |
          clang-r547379.tar.gz
          clang-r563880c.tar.gz
